// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0_eXndY1Fgyjufn0ugVOlKXoujyHdT4',
    appId: '1:388593588261:web:fbaf45caed0d18db3887cc',
    messagingSenderId: '388593588261',
    projectId: 'aplikasi-berita-uts-1aec8',
    authDomain: 'aplikasi-berita-uts-1aec8.firebaseapp.com',
    storageBucket: 'aplikasi-berita-uts-1aec8.firebasestorage.app',
    measurementId: 'G-X2MSNQMJQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWEShkOZ13AWVFzieU5-nFHk6sl3wh1I',
    appId: '1:388593588261:android:c7a2c706a134587a3887cc',
    messagingSenderId: '388593588261',
    projectId: 'aplikasi-berita-uts-1aec8',
    storageBucket: 'aplikasi-berita-uts-1aec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNYaxI7ImK5gypRoYvzqO0E9SullYcABk',
    appId: '1:388593588261:ios:56c198870dac92173887cc',
    messagingSenderId: '388593588261',
    projectId: 'aplikasi-berita-uts-1aec8',
    storageBucket: 'aplikasi-berita-uts-1aec8.firebasestorage.app',
    androidClientId: '388593588261-omj9eu407kibl1jrahvjtr28e395khfh.apps.googleusercontent.com',
    iosClientId: '388593588261-u9b7ino2rk1gl91834qo3vc5kmtlkta3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNYaxI7ImK5gypRoYvzqO0E9SullYcABk',
    appId: '1:388593588261:ios:56c198870dac92173887cc',
    messagingSenderId: '388593588261',
    projectId: 'aplikasi-berita-uts-1aec8',
    storageBucket: 'aplikasi-berita-uts-1aec8.firebasestorage.app',
    androidClientId: '388593588261-omj9eu407kibl1jrahvjtr28e395khfh.apps.googleusercontent.com',
    iosClientId: '388593588261-u9b7ino2rk1gl91834qo3vc5kmtlkta3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX0_eXndY1Fgyjufn0ugVOlKXoujyHdT4',
    appId: '1:388593588261:web:14024c397131a50f3887cc',
    messagingSenderId: '388593588261',
    projectId: 'aplikasi-berita-uts-1aec8',
    authDomain: 'aplikasi-berita-uts-1aec8.firebaseapp.com',
    storageBucket: 'aplikasi-berita-uts-1aec8.firebasestorage.app',
    measurementId: 'G-1DH0EZ4VTG',
  );
}
